name: Video Scraper CI
on: [push, workflow_dispatch]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install playwright
          playwright install chromium
          # Install the virtual display server
          sudo apt-get install -y xvfb

      - name: Run Scraper in Virtual Display
        run: xvfb-run -s "-screen 0 1920x1080x24" python ppv.py
    
      - name: Upload Debug Artifacts
        if: always()  # This ensures it runs even if the scraper fails
        uses: actions/upload-artifact@v4
        with:
          name: scraper-debug-files
          path: |
            debug.png
          retention-days: 5
