name: Pixel Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important: allows the runner to push files back
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright playwright-stealth --upgrade
          playwright install --with-deps chromium

      - name: Run script
        run: python pxl.py

      - name: Commit and Push M3U8
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add pixelsports.m3u8
          git commit -m "Update playlist" || echo "No changes to commit"
          git push
